

all:
	g++ proyecto.cpp principal.cpp -I//home/computacion/opencv/opencvi/include/opencv4/ -L/home/computacion/opencv/opencvi/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -o vision.bin --std=c++17 -lstdc++fs


run:
	./vision.bin